version: '3'
services:
  database:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
  idm:
    image: "flowable/flowable-idm:${FLOWABLE_VERSION}"
    links:
      - database
    environment:
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_USER}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
      - "FLOWABLE_COMMON_APP_IDM-URL=http://idm:8080/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.USER=${ADMIN_USER}"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=${ADMIN_PASSWORD}"
  modeler:
    image: "flowable/flowable-modeler:${FLOWABLE_VERSION}"
    links:
      - idm
      - task
      - database
    environment:
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_USER}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
      - "FLOWABLE_COMMON_APP_IDM-URL=http://idm:8080/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.USER=${ADMIN_USER}"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=${ADMIN_PASSWORD}"
  task:
    image: "flowable/flowable-task:${FLOWABLE_VERSION}"
    links:
      - idm
    environment:
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_USER}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
      - "FLOWABLE_COMMON_APP_IDM-URL=http://idm:8080/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.USER=${ADMIN_USER}"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=${ADMIN_PASSWORD}"
  admin:
    image: "flowable/flowable-admin:${FLOWABLE_VERSION}"
    links:
      - idm
      - task
      - rest
    environment:
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_USER}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
      - "FLOWABLE_COMMON_APP_IDM-URL=http://idm:8080/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.USER=${ADMIN_USER}"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS=http://rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT=8080"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT=flowable-rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT=service"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_USER-NAME=${ADMIN_USER}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS=http://rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT=8080"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT=flowable-rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT=cmmn-api"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_USER-NAME=${ADMIN_USER}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS=http://rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT=8080"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT=flowable-rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT=dmn-api"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_USER-NAME=${ADMIN_USER}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS=http://rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT=8080"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT=flowable-rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT=form-api"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_USER-NAME=${ADMIN_USER}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS=http://rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT=8080"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT=flowable-rest"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT=content-api"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_USER-NAME=${ADMIN_USER}"
      - "FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PASSWORD=${ADMIN_PASSWORD}"
  rest:
    image: "flowable/flowable-rest:${FLOWABLE_VERSION}"
    links:
      - idm
      - database
    environment:
      - "SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DATABASE_USER}"
      - "SPRING_DATASOURCE_USERNAME=${DATABASE_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}"
      - "FLOWABLE_COMMON_APP_IDM-URL=http://idm:8080/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=/flowable-idm"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.USER=${ADMIN_USER}"
      - "FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_REST_APP_ADMIN_USER-ID=${ADMIN_USER}"
      - "FLOWABLE_REST_APP_ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "FLOWABLE_REST_APP_ADMIN_FIRST-NAME=Global"
      - "FLOWABLE_REST_APP_ADMIN_LAST-NAME=Admin"
  httpd:
    image: "httpd:alpine"
    ports:
      - "8080:80"
    volumes:
      - ./httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf